---
# https://docs.docker.com/engine/install/ubuntu/
- name: Download and install Docker GPG key
  become: true
  ansible.builtin.shell:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"
    creates: "/etc/apt/keyrings/docker.asc"

- name: Add Docker repository to apt sources
  become: true
  copy:
    content: |
      deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: get the non root user
  set_fact:
    ansible_user: "{{ ansible_facts['user_id'] }}"

- name: Create the Docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user to the Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: docker_group

